### ISSUE TITLE
Persistance

### ISSUE THREAD

**Issue by ghost** [JanNeuburger/BOBW-Organisation#15]
Enable Save and Load of all Data.
See [Repository.java](https://github.com/JanNeuburger/BOBW-Organisation/blob/master/app/src/main/bobworga/model/Repository.java)

There should be a function to call, wich loads everything right into the Repository, and respective one to save everything from the Repository

**Comment by Maxwahl** [comment]
load Data from DB in background is already enabled.

**Comment by Maxwahl** [comment]
question is how we want to implement saving.
i guess i could just truncate everything when someone wants to save, but should i do it more elegantly?

**Comment by Maxwahl** [comment]
save method is implemented
